### ISSUE TITLE
Wrong amount of lineItems booked in some cases

### ISSUE THREAD

**Issue by maksimhn** [HelpfulHuman/ExperiencesWidgets#85]
Calendar widget - lineItems quantity in orders where custom form fields need to be collected per order, it always books 1 spot instead of a number entered

**Comment by maksimhn** [comment]
@ckeyes88 
so I've been trying to fix the `lineItems` quantity issue in Calendar widget, and here's what I stumbled upon: if there are custom fields requested `per order`, Embedded (which I'm trying to copy) just won't ask for them at all, sending you straight to confirmation page with the following payload:

![image.png](https://images.zenhubusercontent.com/5f36b92a6e124483935cdd83/d2dc0b06-52f6-4405-acb7-a35db6eb62a8)

As you can see it just sends the description of the fields it needs to collect rather than the values themselves.
Is that... a bug? :)

**Comment by siongesteban** [comment]
Hi @maksimhn. I think this is related to theissue that I fixed where the _per order_ form isn't being shown. Here's the [PR](https://github.com/HelpfulHuman/ShopifyExperiencesApp/pull/5011) for that.

**Comment by ckeyes88** [comment]
@maksimhn with regard to only booking 1 spot. I think that might be intentional since essentially the way it works in our system is a little different than the way it works in Shopify's. For us, a line item is an individual attendee whether we have order details or not. So in our system a line item should never have more than 1 quantity since it represents a single attendee to that experience. Does that make sense? Even if on the shopify order there is a line item with 20 units, that gets broken down into 20 experience line items each with quantity = 1.

**Comment by maksimhn** [comment]
@ckeyes88 I think it would be normal if Calendar Widget sent 1 lineItem per attendee (even identical attendees), but it always sends 1 lineItem. Even if we choose 2 or more attendees. But only when Experiences checkout requires additional info per order (that's an important bit since "per customer" and "no additional info" modes work fine). Maybe it's just me. Can you pls confirm if you see it too or not?

**Comment by ckeyes88** [comment]
@maksimhn that does seem strange. It's been so long since we set up that logic that I'm struggling to remember what was expected. Since you're a little closer to this part of the project right now I'll defer to your judgement on what you think should be done. 

If you can reply with what you think should happen, then I can chime in on whether I think that's the right approach.

**Comment by maksimhn** [comment]
@ckeyes88 Here's a video to be sure I'm not imagining things :)
you can see that the timeslots booked are not matching the order


https://user-images.githubusercontent.com/7401417/108449965-39899980-7219-11eb-83a9-e10d5506bc94.mov
